services:
  rabbitmq:
    image: rabbitmq:4.0.7-management
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  image-processor:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq